version: "3.1"

services:
 web:
  depends_on: 
    - db
  build: .
  image: brunozaccariello/sgehookah
  command: sh -c "find . -path "*/migrations/*.py" -not -name "__init__.py" -delete &&
                  find . -path "*/migrations/*.pyc"  -delete &&
                  python3 ./SGEHookah/manage.py makemigrations --noinput && 
                  python3 ./SGEHookah/manage.py migrate &&
                  python3 ./SGEHookah/manage.py initadmin &&
                  python3 ./SGEHookah/manage.py runserver 0.0.0.0:8000"
  volumes: 
    - .:/SGEHookah
  ports:
    - "80:8000"
 db:
  image: postgres:10.4
  environment:
    - PGDATA=/var/lib/postgresql/data/pgdata
    - POSTGRES_PASSWORD=admin123
  volumes:
    - sge-db-data:/var/lib/postgresql/data/pgdata
volumes:
  sge-db-data:
